//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARS.Applications.VETS.Plugins.ShiftTableCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STARS.Applications.VETS.Plugins.ShiftTableCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform Calculation.
        /// </summary>
        internal static string CalculateShiftTable {
            get {
                return ResourceManager.GetString("CalculateShiftTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom field &quot;{0}&quot; does not exist for shift table resources. The custom field must be added for shift table resources..
        /// </summary>
        internal static string CustomFeildDoesNotExistInShiftTableResourceErrorMessage {
            get {
                return ResourceManager.GetString("CustomFeildDoesNotExistInShiftTableResourceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom field &quot;{0}&quot; does not exist in the vehicle resource &quot;{1}&quot;. The custom field must be added to the vehicle in order for it to be used in shift table calculation..
        /// </summary>
        internal static string CustomFeildDoesNotExistInVehicleResourceErrorMessage {
            get {
                return ResourceManager.GetString("CustomFeildDoesNotExistInVehicleResourceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Table Calculator.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Shift Table Calculator: {0}.
        /// </summary>
        internal static string ErrorMessageHeader {
            get {
                return ResourceManager.GetString("ErrorMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of gears is specified as &quot;{0}&quot;. Gears array cannot have &quot;{1}&quot; elements..
        /// </summary>
        internal static string GearArrayLengthErrorMessage {
            get {
                return ResourceManager.GetString("GearArrayLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~-\\!@#$%^()&amp;*+=|{}[]\&quot;&apos;&lt;&gt;?/:,_�.
        /// </summary>
        internal static string IllegalChars {
            get {
                return ResourceManager.GetString("IllegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid entry for {1}. {1} must be an integer between 3 and 6..
        /// </summary>
        internal static string InvalidNumberOfGearsErrorMessage {
            get {
                return ResourceManager.GetString("InvalidNumberOfGearsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, log folder {0} does not exist. Please Create the folder or change the log directory in the config file before running the shift table calculator tool..
        /// </summary>
        internal static string LogFolderDoesNotExist {
            get {
                return ResourceManager.GetString("LogFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected trace resource &quot;{0}&quot; does not contain any speed vector data..
        /// </summary>
        internal static string MissingTraceSpeedVectorErrorMessage {
            get {
                return ResourceManager.GetString("MissingTraceSpeedVectorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected trace resource &quot;{0}&quot; does not contain any time vector data..
        /// </summary>
        internal static string MissingTraceTimeVectorErrorMessage {
            get {
                return ResourceManager.GetString("MissingTraceTimeVectorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid entry for {1}. {1} must be a non-negative number..
        /// </summary>
        internal static string NonNegativeNumberErrorMessage {
            get {
                return ResourceManager.GetString("NonNegativeNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Shift Table name is null..
        /// </summary>
        internal static string NullShiftNameErrorMessage {
            get {
                return ResourceManager.GetString("NullShiftNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected trace is null..
        /// </summary>
        internal static string NullTraceErrorMessage {
            get {
                return ResourceManager.GetString("NullTraceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected vehicle is null..
        /// </summary>
        internal static string NullVehicleErrorMessage {
            get {
                return ResourceManager.GetString("NullVehicleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt for name.
        /// </summary>
        internal static string PromptForName {
            get {
                return ResourceManager.GetString("PromptForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the time vector does not match the length of the speed vector for the selected trace resource &quot;{0)&quot;..
        /// </summary>
        internal static string TraceTimeSpeedMismatchErrorMessage {
            get {
                return ResourceManager.GetString("TraceTimeSpeedMismatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the time vector does not match the length of the speed vector provided to VectorInput constructor..
        /// </summary>
        internal static string VectorInputTimeSpeedMismatchErrorMessage {
            get {
                return ResourceManager.GetString("VectorInputTimeSpeedMismatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle constant number must be &gt;= 0 and &lt;= 4. &quot;{0}&quot; is not an accapetable value..
        /// </summary>
        internal static string VehicleContantNumberErrorMessage {
            get {
                return ResourceManager.GetString("VehicleContantNumberErrorMessage", resourceCulture);
            }
        }
    }
}
